#!/usr/bin/env perl
use strict;
use warnings;
use 5.010;

use Vitruvius::App;
use Vitruvius::Container;

my $config = Vitruvius::Container->get_service('config');

if ( $config->isa('MooseX::App::Message::Envelope') ) {
    say $config;
    exit $config->exitcode;
}

my $service_path = $config->service_path;

my $service = Vitruvius::Container->get_service($service_path);

say for $service->report_lines->@*;

exit 0;
